export const availableAmenities = [
  "Free WiFi",
  "Parking",
  "Air Conditioning",
  "Swimming Pool",
  "Spa",
  "Fitness Center",
  "Restaurant",
  "Bar",
  "Breakfast",
  "Airport Shuttle",
  "Laundry Service",
  "Dry Cleaning",
  "Business Center",
  "Conference Room",
  "Children's Playground",
  "Pet Friendly",
];

export const availableFacilities = [
  "Elevator",
  "Parking",
  "Concierge",
  "24-Hour Front Desk",
  "Luggage Storage",
  "Currency Exchange",
  "Travel Agency",
  "Pharmacy",
  "Gift Shop",
  "ATM",
  "Car Rental",
  "Tour Desk",
];

export const initialFormData = {
  name: "",
  location: "",
  address: "",
  rating: 0,
  rooms: 0,
  status: "active",
  owner: "",
  description: "",
  stars: 3,
  amenities: [],
  facilities: [],
  contactInfo: {
    phone: "",
    email: "",
  },
  surroundings: {
    nearbyAttractions: [],
    topAttractions: [],
    restaurantsCafes: [],
    naturalBeauty: [],
    publicTransport: [],
    closestAirports: [],
  },
};
