import { StyleSheet } from "react-native";

export function createStyles(colors: Record<string, string>, theme: string) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: 16,
      position: "relative",
      backgroundColor: theme === "light" ? colors.blue : colors.background,
      marginBottom: 12,
    },
    headerTitle: {
      color: theme === "light" ? colors.background : colors.text,
      fontSize: 20,
      fontWeight: "bold",
      flex: 1,
      textAlign: "center",
    },
    iconRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: 72,
      position: "absolute",
      right: 16,
    },
    tabsContainer: {
      flexDirection: "row",
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    tab: {
      flex: 1,
      marginHorizontal: 4,
      paddingVertical: 8,
      borderRadius: 16,
      alignItems: "center",
    },
    tabText: { fontWeight: "bold" },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 32,
      marginTop: -80,
    },
    illustration: { width: 280, height: 280, marginBottom: 32 },
    emptyTitle: {
      color: colors.text,
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      marginBottom: 8,
      flexShrink: 1,
    },
    emptySubtitle: {
      color: colors.text,
      fontSize: 16,
      textAlign: "center",
      flexShrink: 1,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "flex-end",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalContent: {
      width: "100%",
      backgroundColor: colors.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 20,
      alignItems: "center",
    },
    removeTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 16,
    },
    modalButton: {
      width: "100%",
      backgroundColor: colors.card,
      borderRadius: 10,
      padding: 15,
      marginBottom: 10,
      alignItems: "center",
    },
    modalButtonText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "bold",
    },
    modalCancelButton: {
      width: "100%",
      backgroundColor: colors.card,
      borderRadius: 10,
      padding: 15,
      alignItems: "center",
    },
    modalCancelText: { color: "#FF3B30", fontSize: 16, fontWeight: "bold" },
    modalContainer: {
      flex: 1,
      backgroundColor: colors.background,
      paddingHorizontal: 16,
    },
    modalHeaderContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 16,
      paddingTop: 60,
    },
    modalHeaderText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "bold",
      textAlign: "center",
    },
    modalBody: { marginTop: 24, paddingHorizontal: 8 },
    modalInfoText: {
      color: colors.text,
      fontSize: 14,
      textAlign: "center",
      marginBottom: 20,
      flexShrink: 1,
    },
    // Property modal / details styles
    propertyHeader: {
      width: "100%",
      height: 200,
      borderBottomLeftRadius: 12,
      borderBottomRightRadius: 12,
      overflow: "hidden",
      justifyContent: "flex-end",
      padding: 12,
      backgroundColor: colors.card,
    },
    propertyImage: {
      width: "100%",
      height: "100%",
      position: "absolute",
      top: 0,
      left: 0,
    },
    propertyImagePlaceholder: {
      width: "100%",
      height: "100%",
      backgroundColor: colors.card,
    },
    propertyHeaderText: { flexDirection: "column", zIndex: 2 },
    propertyTitle: { color: colors.text, fontSize: 20, fontWeight: "bold" },
    propertySubtitle: {
      color: colors.textSecondary || colors.icon,
      fontSize: 14,
      marginTop: 4,
    },
    infoRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    infoLabel: { fontSize: 14 },
    infoValue: { fontSize: 14, fontWeight: "600" },
    badge: {
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 8,
      alignSelf: "flex-start",
      marginTop: 8,
    },
    fullWidthButton: {
      width: "100%",
      backgroundColor: colors.primary || "#007AFF",
      padding: 14,
      borderRadius: 10,
      alignItems: "center",
    },
    fullWidthButtonText: { color: "#FFF", fontWeight: "700" },
    ghostButton: {
      width: "100%",
      padding: 14,
      borderRadius: 10,
      alignItems: "center",
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: colors.border || "#E5E5E5",
    },
    ghostButtonText: { color: colors.text, fontWeight: "600" },
    input: {
      width: "100%",
      backgroundColor: colors.card,
      borderRadius: 8,
      padding: 12,
      color: colors.text,
      marginBottom: 10,
    },
    manageButton: {
      backgroundColor: "#007AFF",
      paddingVertical: 14,
      borderRadius: 8,
      width: "100%",
      alignItems: "center",
      marginTop: 10,
    },
    manageButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "bold" },
    // Help Center Modal styles
    helpModalContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    helpModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 16,
      paddingTop: 60,
      backgroundColor: colors.card,
    },
    helpModalHeaderText: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      flex: 1,
      textAlign: "center",
    },
    helpCloseButton: {
      paddingRight: 10,
    },
    helpInfoContainer: {
      backgroundColor: colors.card,
      borderRadius: 8,
      marginHorizontal: 16,
      marginTop: 20,
      padding: 16,
      flexDirection: "row",
      alignItems: "flex-start",
    },
    helpInfoText: {
      fontSize: 14,
      color: colors.textSecondary || colors.icon,
      flex: 1,
      lineHeight: 20,
    },
    helpSectionTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
      paddingHorizontal: 16,
      paddingVertical: 20,
    },
    helpBlueButton: {
      backgroundColor: "#007AFF",
      borderRadius: 8,
      paddingVertical: 16,
      alignItems: "center",
      marginHorizontal: 16,
      marginTop: 20,
    },
    helpBlueButtonText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    helpFaqTabs: {
      flexDirection: "row",
      paddingHorizontal: 16,
      marginTop: 20,
    },
    helpFaqTab: {
      alignItems: "center",
      paddingHorizontal: 10,
      paddingBottom: 5,
    },
    helpFaqTabText: {
      color: colors.textSecondary || colors.icon,
      fontSize: 14,
    },
    helpFaqItem: {
      flexDirection: "column",
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator || colors.border || "#E5E5E5",
    },
    helpFaqItemText: {
      fontSize: 16,
      color: colors.text,
    },
    helpFaqAnswer: {
      fontSize: 14,
      color: colors.textSecondary || colors.icon,
      marginTop: 8,
    },
  });
}
