import { StyleSheet } from "react-native";

const createStyles = (colors: any, theme: string) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    propertySummarySection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginVertical: 16,
      marginHorizontal: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    propertyImageSummary: {
      width: "100%",
      height: 200,
      borderRadius: 8,
      marginBottom: 12,
    },
    propertyNameSummary: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 4,
    },
    propertyAddressSummary: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 8,
    },
    propertyRatingSummary: {
      flexDirection: "row",
      alignItems: "center",
    },
    ratingSummaryBadge: {
      backgroundColor: colors.green,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      marginRight: 8,
    },
    ratingSummaryText: {
      color: "white",
      fontSize: 12,
      fontWeight: "bold",
    },
    bookingDetailsSection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      marginHorizontal: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    bookingDetailRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 8,
    },
    bookingDetailLabel: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    sectionTitleBooking: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 12,
    },
    priceSummarySection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      marginHorizontal: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    priceRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 6,
    },
    priceLabel: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    priceValue: {
      fontSize: 14,
      color: colors.text,
      fontWeight: "500",
    },
    totalPriceRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: colors.separator,
      marginTop: 8,
    },
    totalPriceLabel: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
    },
    totalPriceValue: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.green,
    },
    confirmBookingButton: {
      backgroundColor: colors.blue,
      paddingVertical: 16,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
      marginHorizontal: 16,
      shadowColor: colors.blue,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    confirmBookingButtonText: {
      color: "#ffffff",
      fontSize: 18,
      fontWeight: "bold",
      letterSpacing: 0.5,
    },
    formLabel: {
      fontSize: 14,
      color: colors.text,
      marginBottom: 6,
      marginTop: 8,
    },
    formInput: {
      borderWidth: 1,
      borderColor: colors.separator,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 12,
      backgroundColor: colors.card,
      color: colors.text,
    },
  });

export default createStyles;
