import { Platform, StatusBar, StyleSheet } from "react-native";

const createStyles = (colors: any, theme: string) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 60,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      paddingBottom: 8,
      paddingHorizontal: 16,
      zIndex: 10,
      backgroundColor:
        theme === "dark" ? "rgba(0,0,0,0.7)" : `${colors.blue}E6`,
    },
    headerScrolled: {
      backgroundColor: theme === "dark" ? colors.background : colors.blue,
      justifyContent: "center",
      alignItems: "center",
    },
    propertyNameHeader: {
      fontSize: 18,
      fontWeight: "bold",
      color: "white",
      textAlign: "center",
      flex: 1,
      marginHorizontal: 60,
    },
    headerButton: {
      backgroundColor: "rgba(0,0,0,0.5)",
      borderRadius: 20,
      width: 40,
      height: 40,
      justifyContent: "center",
      alignItems: "center",
    },
    headerButtonScrolled: {
      backgroundColor:
        theme === "light" ? "rgba(0,0,0,0.1)" : "rgba(255,255,255,0.1)",
    },
    imageGallery: {
      height: 300,
      backgroundColor: colors.card,
    },
    mainImage: {
      width: "100%",
      height: "100%",
      position: "relative",
    },
    imageGrid: {
      position: "absolute",
      bottom: 10,
      right: 10,
      flexDirection: "row",
    },
    thumbnailContainer: {
      marginLeft: 5,
      borderRadius: 8,
      overflow: "hidden",
    },
    thumbnail: {
      width: 60,
      height: 80,
      borderRadius: 8,
    },
    moreImagesOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.6)",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 8,
    },
    moreImagesText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    flexibleSectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      marginTop: 24,
      marginBottom: 8,
    },
    flexibleSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 12,
    },
    durationRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 16,
    },
    durationButton: {
      flex: 1,
      paddingVertical: 12,
      marginHorizontal: 4,
      borderRadius: 8,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.separator,
      alignItems: "center",
    },
    durationButtonActive: {
      backgroundColor: colors.button,
      borderColor: colors.button,
    },
    durationButtonText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "normal",
    },
    durationButtonTextActive: {
      color: colors.background,
      fontWeight: "normal",
    },
    monthsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 16,
    },
    monthButton: {
      flex: 1,
      paddingVertical: 12,
      marginHorizontal: 4,
      borderRadius: 8,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.separator,
      alignItems: "center",
    },
    monthButtonActive: {
      backgroundColor: colors.button,
      borderColor: colors.button,
    },
    monthButtonText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "normal",
    },
    monthButtonTextActive: {
      color: colors.background,
      fontWeight: "bold",
    },
    monthButtonYear: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    flexibleResult: {
      marginTop: 16,
      alignItems: "center",
      padding: 12,
      backgroundColor: colors.card,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.separator,
    },
    flexibleResultText: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "bold",
    },
    content: {
      flex: 1,
      backgroundColor: colors.background,
    },
    propertyHeader: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    propertyName: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 8,
    },
    ratingRowHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    starBadge: {
      backgroundColor: colors.yellow,
      width: 12,
      height: 12,
      marginRight: 2,
    },
    ratingScore: {
      backgroundColor: colors.blue,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      marginLeft: 10,
    },
    ratingScoreText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    bookingSection: {
      padding: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    dateRow: {
      flexDirection: "row",
      marginBottom: 16,
    },
    dateColumn: {
      flex: 1,
    },
    dateLabel: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    dateValue: {
      fontSize: 16,
      color: colors.blue,
      fontWeight: "600",
    },
    roomGuestInfo: {
      marginBottom: 16,
    },
    roomGuestText: {
      fontSize: 16,
      color: colors.blue,
      fontWeight: "600",
    },
    noAvailabilityText: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 16,
    },
    alternativesRow: {
      flexDirection: "row",
    },
    alternativeOption: {
      borderWidth: 1,
      borderColor: colors.blue,
      borderRadius: 8,
      padding: 12,
      marginRight: 10,
      alignItems: "center",
      minWidth: 80,
    },
    alternativeDateRange: {
      fontSize: 12,
      color: colors.blue,
      fontWeight: "600",
      textAlign: "center",
    },
    alternativePrice: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 4,
      textAlign: "center",
    },
    mapSection: {
      height: 200,
      backgroundColor: colors.card,
      marginBottom: 16,
      borderRadius: 8,
      overflow: "hidden",
    },
    mapView: {
      flex: 1,
    },
    mapOverlay: {
      position: "absolute",
      bottom: 20,
      left: 20,
      right: 20,
      backgroundColor: colors.background,
      borderRadius: 8,
      padding: 12,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    addressText: {
      fontSize: 14,
      color: colors.text,
    },
    ratingSection: {
      padding: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    overallRating: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    ratingLabel: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.text,
      marginRight: 10,
    },
    ratingDetails: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    ratingBreakdown: {
      marginTop: 16,
    },
    ratingRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
      justifyContent: "space-between",
    },
    ratingCategory: {
      fontSize: 14,
      color: colors.text,
      minWidth: 80,
    },
    ratingBar: {
      flex: 1,
      height: 8,
      backgroundColor: colors.card,
      borderRadius: 4,
      marginHorizontal: 12,
    },
    ratingBarFill: {
      height: "100%",
      backgroundColor: colors.blue,
      borderRadius: 4,
    },
    ratingValue: {
      fontSize: 14,
      color: colors.text,
      fontWeight: "600",
      minWidth: 30,
      textAlign: "right",
    },
    showMoreButton: {
      marginTop: 16,
    },
    showMoreText: {
      fontSize: 16,
      color: colors.blue,
      fontWeight: "600",
    },
    reviewsSection: {
      padding: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 16,
    },
    reviewCard: {
      marginBottom: 16,
    },
    reviewHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    reviewerInitial: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.accent,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    reviewerInitialText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    reviewerName: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    reviewerCountry: {
      fontSize: 12,
      color: colors.textSecondary,
      marginLeft: 8,
    },
    reviewText: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
    },
    facilitiesSection: {
      padding: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    facilitiesGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    facilityItem: {
      flexDirection: "row",
      alignItems: "center",
      width: "48%",
      marginBottom: 12,
    },
    facilityText: {
      fontSize: 14,
      color: colors.text,
      marginLeft: 8,
      flex: 1,
    },
    seeAllFacilitiesText: {
      fontSize: 16,
      color: colors.blue,
      fontWeight: "600",
      marginTop: 8,
    },
    questionsSection: {
      padding: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    questionCard: {
      backgroundColor: colors.card,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
    },
    questionText: {
      fontSize: 14,
      color: colors.text,
      marginBottom: 12,
      lineHeight: 20,
    },
    answerCard: {
      backgroundColor: colors.cardSecondary || colors.card,
      borderRadius: 8,
      padding: 12,
      marginTop: 8,
    },
    answerDate: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    answerText: {
      fontSize: 14,
      color: colors.text,
    },
    askQuestionButton: {
      borderWidth: 1,
      borderColor: colors.blue,
      backgroundColor: theme === "dark" ? colors.blue : "transparent",
      borderRadius: 8,
      paddingVertical: 12,
      alignItems: "center",
      marginBottom: 12,
    },
    askQuestionText: {
      color: theme === "dark" ? "white" : colors.blue,
      fontSize: 16,
      fontWeight: "600",
    },
    replyTimeText: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 8,
    },
    reviewsSummaryModalContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    reviewsSummaryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    reviewsSummaryTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
      flex: 1,
      textAlign: "center",
    },
    reviewsSummaryCloseButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: colors.card,
    },
    reviewsSummaryStats: {
      padding: 20,
      alignItems: "center",
      backgroundColor: colors.card,
      marginHorizontal: 16,
      marginTop: 16,
      borderRadius: 12,
      elevation: 1,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    reviewsSummaryRating: {
      fontSize: 48,
      fontWeight: "bold",
      color: colors.blue,
      marginBottom: 8,
    },
    reviewsSummaryRatingText: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 4,
    },
    reviewsSummaryCount: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 16,
    },
    reviewsSummaryBars: {
      width: "100%",
      marginTop: 8,
    },
    reviewsSummaryBarRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    reviewsSummaryBarLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      minWidth: 80,
    },
    reviewsSummaryBar: {
      flex: 1,
      height: 6,
      backgroundColor: colors.separator,
      borderRadius: 3,
      marginHorizontal: 12,
      overflow: "hidden",
    },
    reviewsSummaryBarFill: {
      height: "100%",
      backgroundColor: colors.blue,
      borderRadius: 3,
    },
    reviewsSummaryBarValue: {
      fontSize: 12,
      color: colors.text,
      fontWeight: "600",
      minWidth: 30,
      textAlign: "right",
    },
    reviewsSummaryContent: {
      flex: 1,
      paddingHorizontal: 16,
    },
    reviewsSummaryListTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      marginVertical: 16,
    },
    reviewsSummaryCard: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      elevation: 1,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    reviewsSummaryCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    reviewsSummaryAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.blue,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    reviewsSummaryAvatarText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    reviewsSummaryReviewerInfo: {
      flex: 1,
    },
    reviewsSummaryReviewerName: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 2,
    },
    reviewsSummaryReviewerCountry: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    reviewsSummaryReviewText: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
    },
    fixedBookingButton: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.background,
      paddingHorizontal: 20,
      paddingVertical: 15,
      paddingBottom: Platform.OS === "ios" ? 30 : 50,
      borderTopWidth: 1,
      borderTopColor: colors.separator,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    bookNowButton: {
      backgroundColor: colors.button,
      paddingVertical: 16,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.button,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    bookNowButtonText: {
      color: "#ffffff",
      fontSize: 18,
      fontWeight: "bold",
      letterSpacing: 0.5,
    },
    bookingSummaryContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    bookingSummaryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    bookingSummaryTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
    },
    bookingSummaryCloseButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: colors.card,
    },
    bookingSummaryContent: {
      flex: 1,
      paddingHorizontal: 20,
    },
    propertySummarySection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginVertical: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    propertyImageSummary: {
      width: "100%",
      height: 200,
      borderRadius: 8,
      marginBottom: 12,
    },
    propertyNameSummary: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 4,
    },
    propertyAddressSummary: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 8,
    },
    propertyRatingSummary: {
      flexDirection: "row",
      alignItems: "center",
    },
    ratingSummaryBadge: {
      backgroundColor: colors.green,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      marginRight: 8,
    },
    ratingSummaryText: {
      color: colors.background,
      fontSize: 12,
      fontWeight: "bold",
    },
    bookingDetailsSection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    bookingDetailRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 8,
    },
    bookingDetailLabel: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    sectionTitleBooking: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 12,
    },
    priceSummarySection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    priceRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 6,
    },
    priceLabel: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    priceValue: {
      fontSize: 14,
      color: colors.text,
      fontWeight: "500",
    },
    totalPriceRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: colors.separator,
      marginTop: 8,
    },
    totalPriceLabel: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
    },
    totalPriceValue: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.green,
    },
    confirmBookingButton: {
      backgroundColor: colors.blue,
      paddingVertical: 16,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
      shadowColor: colors.blue,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    confirmBookingButtonText: {
      color: "#ffffff",
      fontSize: 18,
      fontWeight: "bold",
      letterSpacing: 0.5,
    },
    paymentConfirmationContainer: {
      flex: 1,
      backgroundColor: colors.background,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    successIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.green,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 24,
    },
    successTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.text,
      textAlign: "center",
      marginBottom: 12,
    },
    successMessage: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: "center",
      lineHeight: 24,
      marginBottom: 32,
    },
    bookingReference: {
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: 12,
      marginBottom: 32,
      width: "100%",
    },
    referenceLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    referenceNumber: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      textAlign: "center",
    },
    doneButton: {
      backgroundColor: colors.button,
      paddingVertical: 14,
      paddingHorizontal: 32,
      borderRadius: 8,
      alignItems: "center",
    },
    doneButtonText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: "bold",
    },
    imageGalleryOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
    },
    descriptionSection: {
      padding: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    descriptionText: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
    },
    readMoreButton: {
      marginTop: 8,
    },
    readMoreText: {
      color: colors.blue,
      fontWeight: "600",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-start",
      alignItems: "center",
      paddingTop: Platform.OS === "ios" ? 64 : (StatusBar.currentHeight ?? 36),
      marginTop: Platform.OS === "ios" ? 12 : 0,
      paddingBottom: 24,
    },
    modalContainer: {
      width: "90%",
      maxWidth: 520,
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 16,
    },
    monthHeader: {
      color: colors.text,
      fontSize: 20,
      fontWeight: "bold",
      marginVertical: 15,
    },
    calendarGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
    },
    calendarDayHeader: {
      width: "14%",
      textAlign: "center",
      color: colors.textSecondary,
      marginBottom: 10,
      fontSize: 14,
      fontWeight: "600",
    },
    calendarDay: {
      width: "14%",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 10,
      minHeight: 40,
      borderRadius: 20,
    },
    selectedDay: {
      backgroundColor: colors.button,
    },
    selectedDayText: {
      color: colors.background,
      fontWeight: "bold",
    },
    rangeDay: {
      backgroundColor: `${colors.button}20`,
    },
    rangeDayText: {
      color: colors.button,
    },
    calendarDayText: {
      color: colors.text,
      fontSize: 16,
    },
    modalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.text,
    },
    modalCloseButton: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: colors.card,
    },
    modalContent: {
      maxHeight: 400,
    },
    modalItem: {
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    modalItemLast: {
      borderBottomWidth: 0,
    },
    datesModalTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.text,
      margin: 12,
    },
    datesPlaceholder: {
      alignItems: "center",
      padding: 24,
      borderRadius: 8,
      backgroundColor: colors.card,
    },
    datesPlaceholderTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
      marginTop: 12,
    },
    datesPlaceholderText: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 8,
      textAlign: "center",
    },
    tempDateButton: {
      marginTop: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      backgroundColor: colors.button,
      borderRadius: 8,
    },
    tempDateButtonText: {
      color: "white",
      fontWeight: "600",
    },
    imageModalContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    imageModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    imageModalCloseButton: {
      padding: 8,
    },
    imageModalTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.text,
    },
    imageModalScrollView: {
      flex: 1,
    },
    imageModalContent: {
      padding: 16,
      alignItems: "center",
    },
    fullImageContainer: {
      marginBottom: 16,
      width: "100%",
    },
    fullImage: {
      width: "100%",
      height: 300,
      borderRadius: 8,
    },
    formLabel: {
      fontSize: 14,
      color: colors.text,
      marginBottom: 6,
    },
    formInput: {
      borderWidth: 1,
      borderColor: colors.separator,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 12,
      backgroundColor: colors.card,
      color: colors.text,
    },
    formInputMultiline: {
      height: 100,
      textAlignVertical: "top",
    },
    submitButton: {
      backgroundColor: colors.button,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: "center",
    },
    submitButtonDisabled: {
      opacity: 0.6,
    },
    submitButtonText: {
      color: "white",
      fontWeight: "600",
      fontSize: 16,
    },
  });

export default createStyles;
