import { Platform, StyleSheet } from "react-native";

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    searchBar: {
      backgroundColor: colors.background,
      paddingHorizontal: 15,
      paddingTop: Platform.OS === "android" ? 10 : 0,
      paddingBottom: Platform.OS === "android" ? 10 : 5,
      marginTop: Platform.OS === "ios" ? -30 : 0,
    },
    expandedHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: Platform.OS === "android" ? -40 : -40,
      position: "relative",
    },
    expandedCloseButton: {
      position: "absolute",
      left: 0,
      padding: 5,
    },
    editSearchText: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      textAlign: "center",
    },
    expandableContainer: {
      overflow: "hidden",
      borderWidth: 2,
      borderColor: "#FFD700", // Yellow border around all expanded inputs
      borderRadius: 12,
      backgroundColor: colors.card,
      padding: 8,
    },
    searchInput: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.card,
      borderRadius: 8,
      padding: 12,
      marginBottom: 10,
      borderWidth: 2,
      borderColor: "#FFD700", // Yellow border for all search inputs
    },
    searchInputExpanded: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.card,
      borderRadius: 8,
      padding: 12,
      marginBottom: Platform.OS === "android" ? 5 : 10,
    },
    searchIcon: {
      marginRight: 10,
    },
    searchInputText: {
      color: colors.text,
      fontSize: 16,
    },
    searchButton: {
      backgroundColor: colors.button,
      padding: 15,
      borderRadius: 8,
      alignItems: "center",
      marginBottom: 20,
    },
    searchButtonText: {
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "bold",
    },
    actionButtons: {
      flexDirection: "row",
      justifyContent: "space-around",
      paddingVertical: 2,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      backgroundColor: colors.background,
    },
    actionButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: 2,
      minWidth: 80,
    },
    actionIcon: {
      marginRight: 8,
    },
    actionText: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "600",
    },
    actionButtonContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    redIndicator: {
      position: "absolute",
      left: -10,
      top: -2,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: "#FF3B30",
      zIndex: 1,
    },
    listContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    cardContainer: {
      backgroundColor: colors.card,
      borderRadius: 10,
      margin: 15,
      overflow: "hidden",
    },
    cardImage: {
      width: "100%",
      height: 200,
      resizeMode: "cover",
    },
    cardContent: {
      padding: 15,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
    },
    ratingContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 5,
    },
    ratingText: {
      fontSize: 14,
      fontWeight: "bold",
      color: colors.background,
      backgroundColor: colors.green,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      marginRight: 5,
    },
    ratingLabel: {
      fontSize: 14,
      color: colors.green,
      fontWeight: "bold",
      marginRight: 5,
    },
    reviews: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    description: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 10,
    },
    price: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.accent,
      marginTop: 10,
    },
    oldPrice: {
      fontSize: 14,
      textDecorationLine: "line-through",
      color: colors.textSecondary,
      marginRight: 5,
    },
    modalContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.background,
      zIndex: 10,
      paddingTop: 50,
    },
    closeButton: {
      padding: 15,
      color: colors.text,
    },
    modalSearchInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      padding: 15,
      margin: 15,
      color: colors.text,
      fontSize: 16,
      borderWidth: 2,
      borderColor: "#FFD700", // Yellow border
    },
    modalTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "bold",
      marginHorizontal: 15,
      marginTop: 10,
    },
    modalItem: {
      color: colors.text,
      fontSize: 16,
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    modalItemContainer: {
      backgroundColor: colors.card,
    },
    noResults: {
      color: colors.textSecondary,
      fontSize: 16,
      padding: 20,
      textAlign: "center",
      fontStyle: "italic",
    },
    noMatchBanner: {
      backgroundColor: colors.card,
      padding: 12,
      margin: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.separator,
      // layout children in a column and center them
      flexDirection: "column",
      alignItems: "center",
    },
    noMatchLeft: {
      // icon container — make it a square and center contents
      width: 48,
      height: 48,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 0,
      marginBottom: 8,
    },
    noMatchBody: {
      flex: 1,
      justifyContent: "center",
      // center text horizontally within the body
      alignItems: "center",
    },
    noMatchAction: {
      // center action button and add top margin
      alignSelf: "center",
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.button,
      borderRadius: 8,
      marginTop: 12,
    },
    noMatchActionText: {
      color: colors.background,
      fontWeight: "600",
    },
    noMatchTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 6,
      textAlign: "center",
    },
    noMatchSubtitle: {
      color: colors.textSecondary,
      fontSize: 14,
      textAlign: "center",
    },
    tabContainer: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      marginHorizontal: 15,
    },
    tab: {
      flex: 1,
      paddingVertical: 15,
      alignItems: "center",
      borderBottomWidth: 2,
      borderBottomColor: "transparent",
    },
    activeTab: {
      borderBottomColor: colors.button,
    },
    tabText: {
      fontSize: 16,
      color: colors.textSecondary,
    },
    activeTabText: {
      color: colors.button,
      fontWeight: "bold",
    },
    selectedDay: {
      backgroundColor: colors.button,
    },
    selectedDayText: {
      color: colors.background,
      fontWeight: "bold",
    },
    rangeDay: {
      backgroundColor: `${colors.button}20`,
    },
    rangeDayText: {
      color: colors.button,
    },
    selectedDatesInfo: {
      backgroundColor: colors.card,
      padding: 15,
      marginHorizontal: 15,
      marginBottom: 15,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.button,
    },
    selectedDatesText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "bold",
      textAlign: "center",
    },
    flexibleSectionTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
      marginTop: 25,
      marginBottom: 15,
    },
    flexibleSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 15,
    },
    durationRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginBottom: 20,
    },
    durationButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 25,
      borderWidth: 1,
      borderColor: colors.separator,
      backgroundColor: colors.card,
    },
    durationButtonActive: {
      borderColor: colors.button,
      backgroundColor: colors.button,
    },
    durationButtonText: {
      color: colors.text,
      fontSize: 16,
    },
    durationButtonTextActive: {
      color: colors.background,
      fontWeight: "bold",
    },
    monthsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 15,
      marginBottom: 30,
    },
    monthButton: {
      flex: 1,
      minWidth: "22%",
      aspectRatio: 1,
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: colors.separator,
      alignItems: "center",
      justifyContent: "center",
      padding: 15,
    },
    monthButtonActive: {
      borderColor: colors.button,
      backgroundColor: colors.button,
    },
    monthButtonText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "bold",
      marginTop: 5,
    },
    monthButtonTextActive: {
      color: colors.background,
    },
    monthButtonYear: {
      color: colors.textSecondary,
      fontSize: 14,
      marginTop: 2,
    },
    flexibleResult: {
      backgroundColor: colors.card,
      padding: 20,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 30,
    },
    flexibleResultText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "bold",
    },
    datesHeader: {
      alignItems: "center",
      paddingVertical: 15,
    },
    datesHeaderText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "bold",
    },
    monthHeader: {
      color: colors.text,
      fontSize: 20,
      fontWeight: "bold",
      marginVertical: 15,
    },
    calendarGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
    },
    calendarDayHeader: {
      width: "14%",
      textAlign: "center",
      color: colors.textSecondary,
      marginBottom: 10,
      fontSize: 14,
      fontWeight: "600",
    },
    calendarDay: {
      width: "14%",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 10,
      minHeight: 40,
      borderRadius: 20,
    },
    calendarDayText: {
      color: colors.text,
      fontSize: 16,
    },
    applyButton: {
      backgroundColor: colors.button,
      padding: 15,
      borderRadius: 8,
      alignItems: "center",
      margin: 15,
    },
    applyButtonText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: "bold",
    },
    modalHeaderTitle: {
      color: colors.text,
      fontSize: 22,
      fontWeight: "bold",
      padding: 15,
    },
    guestRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    guestLabel: {
      color: colors.text,
      fontSize: 18,
    },
    stepper: {
      flexDirection: "row",
      alignItems: "center",
    },
    stepperButton: {
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.button,
      padding: 8,
      borderRadius: 4,
      width: 32,
      height: 32,
      alignItems: "center",
      justifyContent: "center",
    },
    stepperButtonDisabled: {
      borderColor: colors.separator,
      backgroundColor: colors.card,
    },
    stepperButtonText: {
      color: colors.button,
    },
    stepperButtonTextDisabled: {
      color: colors.separator,
    },
    stepperText: {
      color: colors.text,
      fontSize: 18,
      marginHorizontal: 20,
      minWidth: 30,
      textAlign: "center",
    },
    guestLabelContainer: {
      flex: 1,
    },
    guestSubLabel: {
      color: colors.textSecondary,
      fontSize: 14,
      marginTop: 2,
    },
    toggleSwitch: {
      width: 50,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.separator,
      padding: 2,
      justifyContent: "center",
    },
    toggleSwitchActive: {
      backgroundColor: colors.button,
    },
    toggleHandle: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.background,
      alignSelf: "flex-start",
    },
    toggleHandleActive: {
      alignSelf: "flex-end",
    },
    childAgesSection: {
      marginTop: 20,
      paddingHorizontal: 15,
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: colors.separator,
    },
    childAgesSectionTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 10,
    },
    childAgesSectionSubtitle: {
      color: colors.textSecondary,
      fontSize: 14,
      marginBottom: 20,
      lineHeight: 20,
    },
    childAgeRow: {
      marginBottom: 20,
    },
    childAgeLabel: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "500",
      marginBottom: 10,
    },
    required: {
      color: colors.accent,
    },
    ageDropdownContainer: {
      borderWidth: 1,
      borderColor: colors.separator,
      borderRadius: 8,
      padding: 15,
      backgroundColor: colors.card,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    ageDropdownText: {
      color: colors.textSecondary,
      fontSize: 16,
      marginBottom: 10,
    },
    ageDropdownArrow: {
      color: colors.textSecondary,
    },
    // Age selection modal styles
    ageModalContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    ageModalHeader: {
      paddingVertical: 20,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      alignItems: "center",
    },
    ageModalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
    },
    ageList: {
      flex: 1,
    },
    ageItem: {
      paddingVertical: 15,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      backgroundColor: colors.card,
    },
    ageItemText: {
      fontSize: 16,
      color: colors.text,
    },
    ageModalDoneButton: {
      backgroundColor: colors.button,
    },
    ageModalDoneButtonText: {
      color: colors.buttonText,
      fontSize: 16,
      fontWeight: "bold",
    },
    // Filter modal specific styles
    filterSection: {
      marginBottom: 25,
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    sectionSubtitle: {
      color: colors.textSecondary,
      fontSize: 14,
      marginBottom: 15,
      lineHeight: 18,
    },
    checkboxSelected: {
      backgroundColor: colors.button,
      borderColor: colors.button,
    },
    showMoreButton: {
      paddingVertical: 10,
      marginTop: 10,
    },
    showMoreText: {
      color: colors.button,
      fontSize: 14,
      fontWeight: "500",
    },
    // Price slider styles
    priceSliderContainer: {
      marginVertical: 15,
    },
    priceBar: {
      width: 4,
      marginHorizontal: 1,
      borderRadius: 2,
    },
    priceBarInactive: {
      backgroundColor: colors.separator,
    },
    sliderTrackContainer: {
      marginTop: 15,
      paddingHorizontal: 10,
    },
    sliderTrack: {
      height: 4,
      backgroundColor: colors.separator,
      borderRadius: 2,
      position: "relative",
      marginVertical: 15,
    },
    sliderActiveRange: {
      height: 4,
      backgroundColor: colors.button,
      borderRadius: 2,
      position: "absolute",
      top: 0,
    },
    sliderThumb: {
      width: 30,
      height: 30,
      position: "absolute",
      top: -13,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 15,
    },
    sliderThumbInner: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.button,
      borderWidth: 3,
      borderColor: colors.background,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    sliderThumbActive: {
      width: 26,
      height: 26,
      borderRadius: 13,
      borderWidth: 4,
      transform: [{ scale: 1.1 }],
    },
    priceRangeDisplay: {
      alignItems: "center",
      paddingVertical: 10,
    },
    priceRangeText: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    // Counter styles
    counterItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    counterLabel: {
      color: colors.text,
      fontSize: 16,
      flex: 1,
    },
    counterControls: {
      flexDirection: "row",
      alignItems: "center",
    },
    counterButton: {
      width: 36,
      height: 36,
      borderRadius: 4,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.separator,
      alignItems: "center",
      justifyContent: "center",
    },
    counterButtonDisabled: {
      backgroundColor: colors.background,
      borderColor: colors.separator,
    },
    counterButtonText: {
      color: colors.button,
      fontSize: 18,
      fontWeight: "600",
    },
    counterButtonTextDisabled: {
      color: colors.separator,
    },
    counterValue: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "500",
      marginHorizontal: 15,
      minWidth: 30,
      textAlign: "center",
    },
    ageModalDoneText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: "bold",
    },
    mapCloseButton: {
      backgroundColor: colors.background,
      borderRadius: 50,
      padding: 5,
      color: colors.text,
    },
    mapTopHeader: {
      position: "absolute",
      top: 50,
      left: 15,
      right: 15,
      zIndex: 20,
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
    },
    mapLocationInputContainer: {
      flex: 1,
      backgroundColor: colors.background,
      borderRadius: 25,
      paddingHorizontal: 15,
      paddingVertical: 8,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      borderWidth: 2,
      borderColor: "#FFD700",
    },
    mapLocationInput: {
      flex: 1,
      fontSize: 16,
      color: colors.text,
      paddingRight: 10,
    },
    mapLocationInputIcon: {
      marginLeft: 5,
    },
    mapContainer: {
      flex: 1,
    },
    mapImage: {
      ...StyleSheet.absoluteFillObject,
      width: "100%",
      height: "100%",
    },
    mapHeader: {
      position: "absolute",
      top: 50,
      left: 60,
      backgroundColor: colors.background,
      borderRadius: 20,
      paddingVertical: 8,
      paddingHorizontal: 15,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    mapHeaderText: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.text,
    },
    mapActions: {
      position: "absolute",
      bottom: 50,
      right: 15,
      flexDirection: "column",
      alignItems: "center",
    },
    mapActionButton: {
      backgroundColor: colors.background,
      borderRadius: 50,
      padding: 12,
      marginVertical: 5,
      elevation: 5,
    },
    mapActionButtonText: {
      color: colors.text,
    },
    filterHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 15,
      paddingVertical: 10,
      backgroundColor: colors.card,
    },
    filterCloseButton: {
      padding: 5,
      color: colors.text,
    },
    filterTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
    },
    filterReset: {
      fontSize: 16,
      color: colors.button,
    },
    sectionHeader: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.text,
      marginTop: 20,
      marginBottom: 10,
    },
    budgetValue: {
      color: colors.text,
      fontSize: 16,
      marginBottom: 10,
    },
    priceGraphContainer: {
      height: 80,
      marginBottom: 20,
    },
    priceGraph: {
      height: 100,
      flexDirection: "row",
      alignItems: "flex-end",
      justifyContent: "space-between",
      paddingHorizontal: 5,
      backgroundColor: colors.card,
      borderRadius: 8,
      paddingVertical: 10,
    },
    filterItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    filterItemText: {
      color: colors.text,
      fontSize: 16,
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 4,
      // center the check icon
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.textSecondary,
    },
    filterFooter: {
      backgroundColor: colors.card,
      padding: 15,
      borderTopWidth: 1,
      borderTopColor: colors.separator,
    },
    matchCount: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.text,
    },
    subMatchCount: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 10,
    },
    showResultsButton: {
      backgroundColor: colors.button,
      padding: 15,
      borderRadius: 8,
      alignItems: "center",
    },
    showResultsText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: "bold",
    },
    sortHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 15,
      paddingVertical: 10,
      backgroundColor: colors.card,
    },
    sortHeaderIcon: {
      color: colors.text,
    },
    sortTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginLeft: 15,
      color: colors.text,
    },
    sortItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    sortItemText: {
      fontSize: 16,
      color: colors.text,
    },
    radio: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: colors.separator,
    },
    radioSelected: {
      backgroundColor: colors.button,
      borderColor: colors.button,
    },
    secondaryText: {
      color: colors.textSecondary,
    },
    headerContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 15,
      paddingVertical: 10,
      backgroundColor: colors.background,
    },
    backButton: {
      padding: 8,
    },
  });
